---

# Main tasks file for sftp role

- name: 'INIT | Manage variables to use for our target'
  include_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::sftp'
    - 'role::sftp::init'


- name: 'CONFIG | Manage sftp users group'
  become: True
  group:
    name: "{{ sftp_users_group_name }}"
    state: 'present'
  tags:
    - 'role::sftp'
    - 'role::sftp::config'


- name: 'CONFIG | Ensure data path exists'
  become: True
  file:
    path: "{{ sftp_data_dir_path }}"
    owner: "{{ sftp_data_dir_owner }}"
    group: "{{ sftp_data_dir_group }}"
    mode: "{{ sftp_data_dir_mode }}"
    state: 'directory'
  tags:
    - 'role::sftp'
    - 'role::sftp::config'


- name: 'USERS | Manage sftp users'
  become: True
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups | default(sftp_users_group_name) }}"
    createhome: True
    home: "{{ item.home_path | default(sftp_data_dir_path ~ '/' ~ item.name) }}"
    skeleton: "{{ item.skeleton | default(sftp_users_skeleton) }}"
    state: "{{ item.state | default('present') }}"
    shell: "{{ item.shell | default(sftp_users_shell) }}"
  no_log: True
  with_items: "{{ sftp_users }}"
  tags:
    - 'role::sftp'
    - 'role::sftp::users'


- name: 'USERS | Manage permissions on users home directory'
  become: True
  file:
    path: "{{ item.home_path | default(sftp_data_dir_path ~ '/' ~ item.name) }}"
    owner: "{{ item.home_owner | default(sftp_data_dir_owner) }}"
    group: "{{ item.home_group | default(item.name) }}"
    mode: "{{ item.home_mode | default(sftp_users_home_mode) }}"
  no_log: True
  with_items: "{{ sftp_users }}"
  when: "(item.state | default('present')) == 'present'"
  tags:
    - 'role::sftp'
    - 'role::sftp::users'


- name: 'USERS | Manage authorized keys'
  become: True
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.authorized_keys | join('\n') }}"
    exclusive: True
  no_log: True
  with_items: "{{ sftp_users }}"
  when: "(item.state | default('present')) == 'present'"
  tags:
    - 'role::sftp'
    - 'role::sftp::users'
